### PR TITLE
added deg rate to admin commons toast

### PR DESCRIPTION
**Pull request by nhs-wobuzhidao**
Minor change to toast notification when user commons is created by admin so that it also displays chosen degradation rate.

### CODE REVIEW

**Review by MrJacobEisner — APPROVED** [review]
LGTM

**Comment by nhs-wobuzhidao** [comment]
Need to add storybook

**Comment by epuzio** [comment]
LGTM!

**Review by epuzio — APPROVED** [review]
Looks good!

**Pull request closed without merging**
